#!/usr/bin/env python3
"""Build script for story-site (v2, multi-book).

Layout:
  stories/<book-id>/meta.json   — title/subtitle/updated/color/tag
  stories/<book-id>/NN.md       — chapters in order (first `# ` line = chapter title)

Outputs:
  books.js          — window.LIBRARY for the reader (works offline / file://)
  epub/<id>.epub    — one EPUB per book
  assets/icon-*.png — PWA icons (pure-Python PNG)

Usage: python3 build.py
"""
import html
import json
import os
import re
import struct
import zlib
import zipfile

ROOT = os.path.dirname(os.path.abspath(__file__))
STORIES_DIR = os.path.join(ROOT, "stories")
SITE_NAME = "离谱历史书架"


# ---------- minimal markdown -> HTML ----------

def inline(text: str) -> str:
    text = html.escape(text, quote=False)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<em>\1</em>", text)
    return text


def md_to_html(md: str):
    """Return (chapter_title, body_html, char_count). First H1 = chapter title.
    Supports: # ## headings, paragraphs, - lists, ---, > quotes,
    and images: ![caption](relative/path.jpg)
    """
    lines = md.splitlines()
    out = []
    title = ""
    para = []

    def flush():
        nonlocal para
        if para:
            out.append("<p>" + inline(" ".join(para)) + "</p>")
            para = []

    in_list = False
    for line in lines:
        s = line.strip()
        img = re.match(r"^!\[(.*?)\]\((.+?)\)$", s)
        if img:
            flush()
            cap, src = img.group(1), img.group(2)
            fig = f'<figure><img src="{html.escape(src, quote=True)}" alt="{html.escape(cap, quote=True)}" loading="lazy">'
            if cap:
                fig += f"<figcaption>{inline(cap)}</figcaption>"
            fig += "</figure>"
            out.append(fig)
            continue
        if s.startswith("- "):
            flush()
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append("<li>" + inline(s[2:]) + "</li>")
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        if not s:
            flush()
        elif s.startswith("# "):
            flush()
            if not title:
                title = s[2:].strip()
            else:
                out.append("<h2>" + inline(s[2:]) + "</h2>")
        elif s.startswith("## "):
            flush()
            out.append("<h3>" + inline(s[3:]) + "</h3>")
        elif s.startswith("> "):
            flush()
            out.append("<blockquote><p>" + inline(s[2:]) + "</p></blockquote>")
        elif s == "---":
            flush()
            out.append("<hr>")
        else:
            para.append(s)
    flush()
    if in_list:
        out.append("</ul>")
    chars = len(re.sub(r"\s", "", re.sub(r"<[^>]+>", "", "".join(out))))
    return title, "\n".join(out), chars


def load_books():
    books = []
    for bid in sorted(os.listdir(STORIES_DIR)):
        bdir = os.path.join(STORIES_DIR, bid)
        meta_path = os.path.join(bdir, "meta.json")
        if not os.path.isdir(bdir) or not os.path.exists(meta_path):
            continue
        with open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)
        chapters = []
        for name in sorted(os.listdir(bdir)):
            if not name.endswith(".md"):
                continue
            with open(os.path.join(bdir, name), encoding="utf-8") as f:
                t, body, chars = md_to_html(f.read())
            chapters.append({"title": t, "html": body, "chars": chars})
        if not chapters:
            continue
        books.append({
            "id": bid,
            "title": meta.get("title", bid),
            "subtitle": meta.get("subtitle", ""),
            "author": meta.get("author", SITE_NAME),
            "updated": meta.get("updated", ""),
            "color": meta.get("color", "#3d4a5a"),
            "tag": meta.get("tag", ""),
            "order": meta.get("order", 99),
            "chapters": chapters,
            "totalChars": sum(c["chars"] for c in chapters),
        })
    books.sort(key=lambda b: (b["order"], b["updated"]), reverse=False)
    # newest updated first on the shelf
    books.sort(key=lambda b: b["updated"], reverse=True)
    return books


def build_books_js(books):
    path = os.path.join(ROOT, "books.js")
    lib = {"site": SITE_NAME, "books": books}
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by build.py — do not edit by hand\n")
        f.write("window.LIBRARY = ")
        json.dump(lib, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    return path


# ---------- EPUB ----------

def build_epub(book):
    os.makedirs(os.path.join(ROOT, "epub"), exist_ok=True)
    path = os.path.join(ROOT, "epub", f"{book['id']}.epub")
    css = ("body{font-family:sans-serif;line-height:2;}"
           "h1{font-size:1.4em;margin:1.5em 0 1em;}"
           "p{margin:0 0 1em;}hr{margin:2em auto;width:40%;}"
           "img{max-width:100%;}figcaption{font-size:.8em;color:#666;text-align:center;}")

    def xhtml(title, body):
        return f"""<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh">
<head><title>{html.escape(title)}</title>
<link rel="stylesheet" type="text/css" href="style.css"/></head>
<body><h1>{html.escape(title)}</h1>
{body}
</body></html>"""

    manifest_items, spine_items, nav_lis, files = [], [], [], []
    imgs = []
    for i, ch in enumerate(book["chapters"], 1):
        fn = f"ch{i:02d}.xhtml"
        body = ch["html"]
        for m in re.finditer(r'src="([^"]+)"', body):
            imgs.append(m.group(1))
        files.append((fn, xhtml(ch["title"], body)))
        manifest_items.append(f'<item id="ch{i:02d}" href="{fn}" media-type="application/xhtml+xml"/>')
        spine_items.append(f'<itemref idref="ch{i:02d}"/>')
        nav_lis.append(f'<li><a href="{fn}">{html.escape(ch["title"])}</a></li>')

    img_items = []
    for j, rel in enumerate(dict.fromkeys(imgs)):
        src = os.path.join(ROOT, rel)
        if not os.path.exists(src):
            continue
        ext = os.path.splitext(rel)[1].lower()
        mt = {"jpg": "image/jpeg", "jpeg": "image/jpeg", "png": "image/png",
              "gif": "image/gif", "webp": "image/webp"}.get(ext.lstrip("."), "image/jpeg")
        img_items.append((rel, src, f"img{j}", mt))
        manifest_items.append(f'<item id="img{j}" href="{rel}" media-type="{mt}"/>')

    nav = f"""<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="zh">
<head><title>目录</title></head>
<body><nav epub:type="toc"><h1>目录</h1><ol>
{chr(10).join(nav_lis)}
</ol></nav></body></html>"""

    opf = f"""<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="uid" xml:lang="zh">
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
<dc:identifier id="uid">urn:uuid:story-site-{book['id']}</dc:identifier>
<dc:title>{html.escape(book['title'])}</dc:title>
<dc:creator>{html.escape(book['author'])}</dc:creator>
<dc:language>zh</dc:language>
<meta property="dcterms:modified">{book['updated'] or '2026-07-03'}T00:00:00Z</meta>
</metadata>
<manifest>
<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
<item id="css" href="style.css" media-type="text/css"/>
{chr(10).join(manifest_items)}
</manifest>
<spine>
{chr(10).join(spine_items)}
</spine>
</package>"""

    container = """<?xml version="1.0" encoding="utf-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
<rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles>
</container>"""

    with zipfile.ZipFile(path, "w") as z:
        z.writestr("mimetype", "application/epub+zip", compress_type=zipfile.ZIP_STORED)
        z.writestr("META-INF/container.xml", container)
        z.writestr("OEBPS/content.opf", opf)
        z.writestr("OEBPS/nav.xhtml", nav)
        z.writestr("OEBPS/style.css", css)
        for fn, content in files:
            z.writestr(f"OEBPS/{fn}", content)
        for rel, src, _id, _mt in img_items:
            z.write(src, f"OEBPS/{rel}")
    return path


# ---------- PWA icons (pure-Python PNG) ----------

def make_png(size: int, out_path: str):
    bg = (43, 36, 28)       # deep coffee
    fg = (238, 230, 210)    # warm paper
    px = bytearray()
    cx = size / 2
    book_w, book_h = size * 0.52, size * 0.38
    top, bottom = cx - book_h / 2, cx + book_h / 2
    left, right = cx - book_w / 2, cx + book_w / 2
    spine_w = max(2, size // 48)
    for y in range(size):
        row = bytearray()
        for x in range(size):
            c = bg
            if left <= x <= right and top <= y <= bottom:
                dx = abs(x - cx)
                curve = (dx / (book_w / 2)) ** 2 * (size * 0.05)
                if dx > spine_w and y > top + curve:
                    c = fg
            row += bytes(c)
        px += b"\x00" + row

    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
           + chunk(b"IDAT", zlib.compress(bytes(px), 9)) + chunk(b"IEND", b""))
    with open(out_path, "wb") as f:
        f.write(png)


def main():
    books = load_books()
    build_books_js(books)
    for b in books:
        build_epub(b)
    assets = os.path.join(ROOT, "assets")
    os.makedirs(assets, exist_ok=True)
    for s, name in [(512, "icon-512.png"), (192, "icon-192.png"), (180, "apple-touch-icon.png")]:
        make_png(s, os.path.join(assets, name))
    print(f"built: books.js ({len(books)} books), epub/ x{len(books)}, icons x3")
    for b in books:
        print(f"  - {b['id']}: {b['title']} · {len(b['chapters'])}章 · {b['totalChars']}字 · 更新{b['updated']}")


if __name__ == "__main__":
    main()
